name: setup-firebase-emulator
descrption: 'Setup Firebase Emulator Suite' 
runs:
  using: 'composite'
  steps:
    - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Firebase Emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: firebase-emulators-${{ runner.os }}-${{ hashFiles('**/firebase.json') }}
          restore-keys: |
            firebase-emulators-${{ runner.os }}-

      - name: Setup Firebase
        uses: w9jds/setup-firebase@v1.0.0
            
      - name: Run Firestore Emulator Setup
        run: firebase setup:emulators:firestore

      
