name: Build and test code
'on': pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Checkout the repository code

      - name: Setup Node
        uses: ./.github/workflows/setup-node

      - name: Setup Firebase Emulator Suite
        uses: ./.github/workflows/setup-firebase-emulator
        with:
            firebase_token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Cache Next.js build output
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build the app
        run: npm run build

      - name: Run tests
        run: npm run coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Replace with your Codecov token
          file: ./coverage/coverage-final.json # Adjust path if your report differs

